/*
 * Created on 2022-06-09 ( 11:36:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "BatchSpeedTestConfig"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="batch_speed_test_config", schema="public" )
public class BatchSpeedTestConfig implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="guid", nullable=false, length=36)
    private String     guid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="test_name", nullable=false, length=50)
    private String     testName ;

    @Column(name="test_description", length=50)
    private String     testDescription ;

    @Column(name="schedule", nullable=false, length=50)
    private String     schedule ;

    @Column(name="test_definition", length=50)
    private String     testDefinition ;

    @Lob
    @Column(name="test_configuraton", nullable=false)
    private byte[]     testConfiguraton ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public BatchSpeedTestConfig() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setGuid( String guid ) {
        this.guid = guid ;
    }
    public String getGuid() {
        return this.guid;
    }

    public void setTestName( String testName ) {
        this.testName = testName ;
    }
    public String getTestName() {
        return this.testName;
    }

    public void setTestDescription( String testDescription ) {
        this.testDescription = testDescription ;
    }
    public String getTestDescription() {
        return this.testDescription;
    }

    public void setSchedule( String schedule ) {
        this.schedule = schedule ;
    }
    public String getSchedule() {
        return this.schedule;
    }

    public void setTestDefinition( String testDefinition ) {
        this.testDefinition = testDefinition ;
    }
    public String getTestDefinition() {
        return this.testDefinition;
    }

    public void setTestConfiguraton( byte[] testConfiguraton ) {
        this.testConfiguraton = testConfiguraton ;
    }
    public byte[] getTestConfiguraton() {
        return this.testConfiguraton;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(guid);
        sb.append("|");
        sb.append(testName);
        sb.append("|");
        sb.append(testDescription);
        sb.append("|");
        sb.append(schedule);
        sb.append("|");
        sb.append(testDefinition);
        // attribute 'testConfiguraton' not usable (type = byte[])
        return sb.toString(); 
    } 

}
