/*
 * Created on 2022-06-09 ( 11:36:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "GatewayTest"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="gateway_test", schema="public" )
public class GatewayTest implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="guid", nullable=false, length=36)
    private String     guid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="test_id", length=50)
    private String     testId ;

    @Column(name="serial_number", nullable=false, length=50)
    private String     serialNumber ;

    @Column(name="state", nullable=false, length=50)
    private String     state ;

    @Column(name="test_server_guid", nullable=false, length=36)
    private String     testServerGuid ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", nullable=false)
    private Date       createdOn ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="completed_on")
    private Date       completedOn ;

    @Column(name="speed_tests_guid", nullable=false, length=36)
    private String     speedTestsGuid ;

    @Column(name="priority", nullable=false)
    private Integer    priority ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="speed_tests_guid", referencedColumnName="guid", insertable=false, updatable=false)
    private SpeedTest  speedTest ; 

    @OneToMany(mappedBy="gatewayTest")
    private List<GatewayTestResult> listOfGatewayTestResult ; 

    @ManyToOne
    @JoinColumn(name="test_server_guid", referencedColumnName="guid", insertable=false, updatable=false)
    private TestServer testServer ; 


    /**
     * Constructor
     */
    public GatewayTest() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setGuid( String guid ) {
        this.guid = guid ;
    }
    public String getGuid() {
        return this.guid;
    }

    public void setTestId( String testId ) {
        this.testId = testId ;
    }
    public String getTestId() {
        return this.testId;
    }

    public void setSerialNumber( String serialNumber ) {
        this.serialNumber = serialNumber ;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setState( String state ) {
        this.state = state ;
    }
    public String getState() {
        return this.state;
    }

    public void setTestServerGuid( String testServerGuid ) {
        this.testServerGuid = testServerGuid ;
    }
    public String getTestServerGuid() {
        return this.testServerGuid;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCompletedOn( Date completedOn ) {
        this.completedOn = completedOn ;
    }
    public Date getCompletedOn() {
        return this.completedOn;
    }

    public void setSpeedTestsGuid( String speedTestsGuid ) {
        this.speedTestsGuid = speedTestsGuid ;
    }
    public String getSpeedTestsGuid() {
        return this.speedTestsGuid;
    }

    public void setPriority( Integer priority ) {
        this.priority = priority ;
    }
    public Integer getPriority() {
        return this.priority;
    }

    //--- GETTERS FOR LINKS
    public SpeedTest getSpeedTest() {
        return this.speedTest;
    } 

    public List<GatewayTestResult> getListOfGatewayTestResult() {
        return this.listOfGatewayTestResult;
    } 

    public TestServer getTestServer() {
        return this.testServer;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(guid);
        sb.append("|");
        sb.append(testId);
        sb.append("|");
        sb.append(serialNumber);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(testServerGuid);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(completedOn);
        sb.append("|");
        sb.append(speedTestsGuid);
        sb.append("|");
        sb.append(priority);
        return sb.toString(); 
    } 

}
