/*
 * Created on 2022-06-09 ( 11:36:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "GatewayTestHistory"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="gateway_test_history", schema="public" )
public class GatewayTestHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="guid", nullable=false, length=36)
    private String     guid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="gateway_device_guid", nullable=false, length=36)
    private String     gatewayDeviceGuid ;

    @Column(name="speed", nullable=false)
    private Float      speed ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false)
    private Date       createDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="gateway_device_guid", referencedColumnName="guid", insertable=false, updatable=false)
    private GatewayDevice gatewayDevice ; 


    /**
     * Constructor
     */
    public GatewayTestHistory() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setGuid( String guid ) {
        this.guid = guid ;
    }
    public String getGuid() {
        return this.guid;
    }

    public void setGatewayDeviceGuid( String gatewayDeviceGuid ) {
        this.gatewayDeviceGuid = gatewayDeviceGuid ;
    }
    public String getGatewayDeviceGuid() {
        return this.gatewayDeviceGuid;
    }

    public void setSpeed( Float speed ) {
        this.speed = speed ;
    }
    public Float getSpeed() {
        return this.speed;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate ;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- GETTERS FOR LINKS
    public GatewayDevice getGatewayDevice() {
        return this.gatewayDevice;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(guid);
        sb.append("|");
        sb.append(gatewayDeviceGuid);
        sb.append("|");
        sb.append(speed);
        sb.append("|");
        sb.append(createDate);
        return sb.toString(); 
    } 

}
