/*
 * Created on 2022-06-09 ( 11:36:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "GatewayTestResult"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="gateway_test_result", schema="public" )
public class GatewayTestResult implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="guid", nullable=false, length=36)
    private String     guid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="gateway_test_guid", nullable=false, length=36)
    private String     gatewayTestGuid ;

    @Lob
    @Column(name="result")
    private byte[]     result ;

    @Column(name="status", nullable=false, length=50)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="gateway_test_guid", referencedColumnName="guid", insertable=false, updatable=false)
    private GatewayTest gatewayTest ; 


    /**
     * Constructor
     */
    public GatewayTestResult() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setGuid( String guid ) {
        this.guid = guid ;
    }
    public String getGuid() {
        return this.guid;
    }

    public void setGatewayTestGuid( String gatewayTestGuid ) {
        this.gatewayTestGuid = gatewayTestGuid ;
    }
    public String getGatewayTestGuid() {
        return this.gatewayTestGuid;
    }

    public void setResult( byte[] result ) {
        this.result = result ;
    }
    public byte[] getResult() {
        return this.result;
    }

    public void setStatus( String status ) {
        this.status = status ;
    }
    public String getStatus() {
        return this.status;
    }

    //--- GETTERS FOR LINKS
    public GatewayTest getGatewayTest() {
        return this.gatewayTest;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(guid);
        sb.append("|");
        sb.append(gatewayTestGuid);
        // attribute 'result' not usable (type = byte[])
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
