/*
 * Created on 2022-06-09 ( 11:36:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "GatewayDevice"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="gateway_device", schema="public" )
public class GatewayDevice implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="guid", nullable=false, length=36)
    private String     guid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="serial_number", nullable=false, length=50)
    private String     serialNumber ;

    @Column(name="pon", nullable=false, length=50)
    private String     pon ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="gatewayDevice")
    private List<GatewayTestHistory> listOfGatewayTestHistory ; 


    /**
     * Constructor
     */
    public GatewayDevice() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setGuid( String guid ) {
        this.guid = guid ;
    }
    public String getGuid() {
        return this.guid;
    }

    public void setSerialNumber( String serialNumber ) {
        this.serialNumber = serialNumber ;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setPon( String pon ) {
        this.pon = pon ;
    }
    public String getPon() {
        return this.pon;
    }

    //--- GETTERS FOR LINKS
    public List<GatewayTestHistory> getListOfGatewayTestHistory() {
        return this.listOfGatewayTestHistory;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(guid);
        sb.append("|");
        sb.append(serialNumber);
        sb.append("|");
        sb.append(pon);
        return sb.toString(); 
    } 

}
