/*
 * Created on 2022-06-09 ( 11:36:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "MetricGatewayConfig"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="metric_gateway_config", schema="public" )
public class MetricGatewayConfig implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="guid", nullable=false, length=36)
    private String     guid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="key", nullable=false, length=50)
    private String     key ;

    @Column(name="value", length=255)
    private String     value ;

    @Column(name="last_updated", nullable=false, length=50)
    private String     lastUpdated ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public MetricGatewayConfig() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setGuid( String guid ) {
        this.guid = guid ;
    }
    public String getGuid() {
        return this.guid;
    }

    public void setKey( String key ) {
        this.key = key ;
    }
    public String getKey() {
        return this.key;
    }

    public void setValue( String value ) {
        this.value = value ;
    }
    public String getValue() {
        return this.value;
    }

    public void setLastUpdated( String lastUpdated ) {
        this.lastUpdated = lastUpdated ;
    }
    public String getLastUpdated() {
        return this.lastUpdated;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(guid);
        sb.append("|");
        sb.append(key);
        sb.append("|");
        sb.append(value);
        sb.append("|");
        sb.append(lastUpdated);
        return sb.toString(); 
    } 

}
