/*
 * Created on 2022-06-09 ( 11:36:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "MetricGatewayHistory"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="metric_gateway_history", schema="public" )
public class MetricGatewayHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="guid", nullable=false, length=36)
    private String     guid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="test_server_guid", nullable=false, length=36)
    private String     testServerGuid ;

    @Column(name="absolute_load", nullable=false, length=50)
    private String     absoluteLoad ;

    @Column(name="realtive_load", nullable=false, length=50)
    private String     realtiveLoad ;

    @Column(name="calculated_capacity", nullable=false)
    private Integer    calculatedCapacity ;

    @Column(name="running_tests", nullable=false)
    private Integer    runningTests ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="test_server_guid", referencedColumnName="guid", insertable=false, updatable=false)
    private TestServer testServer ; 


    /**
     * Constructor
     */
    public MetricGatewayHistory() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setGuid( String guid ) {
        this.guid = guid ;
    }
    public String getGuid() {
        return this.guid;
    }

    public void setTestServerGuid( String testServerGuid ) {
        this.testServerGuid = testServerGuid ;
    }
    public String getTestServerGuid() {
        return this.testServerGuid;
    }

    public void setAbsoluteLoad( String absoluteLoad ) {
        this.absoluteLoad = absoluteLoad ;
    }
    public String getAbsoluteLoad() {
        return this.absoluteLoad;
    }

    public void setRealtiveLoad( String realtiveLoad ) {
        this.realtiveLoad = realtiveLoad ;
    }
    public String getRealtiveLoad() {
        return this.realtiveLoad;
    }

    public void setCalculatedCapacity( Integer calculatedCapacity ) {
        this.calculatedCapacity = calculatedCapacity ;
    }
    public Integer getCalculatedCapacity() {
        return this.calculatedCapacity;
    }

    public void setRunningTests( Integer runningTests ) {
        this.runningTests = runningTests ;
    }
    public Integer getRunningTests() {
        return this.runningTests;
    }

    //--- GETTERS FOR LINKS
    public TestServer getTestServer() {
        return this.testServer;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(guid);
        sb.append("|");
        sb.append(testServerGuid);
        sb.append("|");
        sb.append(absoluteLoad);
        sb.append("|");
        sb.append(realtiveLoad);
        sb.append("|");
        sb.append(calculatedCapacity);
        sb.append("|");
        sb.append(runningTests);
        return sb.toString(); 
    } 

}
