/*
 * Created on 2022-06-09 ( 11:36:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "SpeedTest"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="speed_test", schema="public" )
public class SpeedTest implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="guid", nullable=false, length=36)
    private String     guid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="test_type", nullable=false, length=50)
    private String     testType ;

    @Column(name="last_updated", nullable=false, length=50)
    private String     lastUpdated ;

    @Column(name="test_name", nullable=false, length=50)
    private String     testName ;

    @Column(name="test_description", length=50)
    private String     testDescription ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="speedTest")
    private List<GatewayTest> listOfGatewayTest ; 


    /**
     * Constructor
     */
    public SpeedTest() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setGuid( String guid ) {
        this.guid = guid ;
    }
    public String getGuid() {
        return this.guid;
    }

    public void setTestType( String testType ) {
        this.testType = testType ;
    }
    public String getTestType() {
        return this.testType;
    }

    public void setLastUpdated( String lastUpdated ) {
        this.lastUpdated = lastUpdated ;
    }
    public String getLastUpdated() {
        return this.lastUpdated;
    }

    public void setTestName( String testName ) {
        this.testName = testName ;
    }
    public String getTestName() {
        return this.testName;
    }

    public void setTestDescription( String testDescription ) {
        this.testDescription = testDescription ;
    }
    public String getTestDescription() {
        return this.testDescription;
    }

    //--- GETTERS FOR LINKS
    public List<GatewayTest> getListOfGatewayTest() {
        return this.listOfGatewayTest;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(guid);
        sb.append("|");
        sb.append(testType);
        sb.append("|");
        sb.append(lastUpdated);
        sb.append("|");
        sb.append(testName);
        sb.append("|");
        sb.append(testDescription);
        return sb.toString(); 
    } 

}
