/*
 * Created on 2022-06-09 ( Date ISO 2022-06-09 - Time 21:04:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.service;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.cs.speedtest.entities.BatchSpeedTestConfig;
import com.cs.speedtest.repository.BatchSpeedTestConfigRepository;

/**
 * Spring persistence service for "BatchSpeedTestConfig" <br>
 * 
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Service

public class BatchSpeedTestConfigPersistenceService {

	@Autowired
	private BatchSpeedTestConfigRepository batchSpeedTestConfigRepository;

	public BatchSpeedTestConfig findById(String guid) {

		Optional<BatchSpeedTestConfig> optionalEntity = batchSpeedTestConfigRepository.findById(guid);
		if (optionalEntity.isPresent()) {
			return optionalEntity.get();
		}
		return null;

	}

	public List<BatchSpeedTestConfig> findAll() {
		// return mapper.mapEntityToRecord(batchSpeedTestConfigRepository.findAll());

		List<BatchSpeedTestConfig> entities = batchSpeedTestConfigRepository.findAll();

		return entities;

	}

	public long countAll() {
		return batchSpeedTestConfigRepository.count();
	}

	public BatchSpeedTestConfig save(BatchSpeedTestConfig record) {
//		return mapper.map(batchSpeedTestConfigRepository.save(mapper.map(record)));
		BatchSpeedTestConfig saved = batchSpeedTestConfigRepository.save(record);
		return saved;

	}

	public boolean update(BatchSpeedTestConfig record) {

		if (exists(record)) {
			batchSpeedTestConfigRepository.save(record);
			return true;
		}
		return false;
	}

	public BatchSpeedTestConfig create(BatchSpeedTestConfig record) {
		BatchSpeedTestConfig saved = batchSpeedTestConfigRepository.save(record);
		return saved;

	}

	public boolean deleteById(String guid) {
		final Optional<BatchSpeedTestConfig> optinalEntity = batchSpeedTestConfigRepository.findById(guid);
		if (!optinalEntity.isPresent()) {
			return false;
		}

		else {
			batchSpeedTestConfigRepository.delete(optinalEntity.get());
			return true;
		}
	}

	public boolean delete(BatchSpeedTestConfig record) {
		if (record == null) {
			return false;
		}
		return deleteById(record.getGuid());

	}

	public boolean exists(String guid) {
		return batchSpeedTestConfigRepository.findById(guid).isPresent();
	}

	public boolean exists(BatchSpeedTestConfig record) {
		return record == null ? false : batchSpeedTestConfigRepository.findById(record.getGuid()).isPresent();
	}

}
