/*
 * Created on 2022-06-09 ( Date ISO 2022-06-09 - Time 21:05:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.service;

import java.util.List;
import java.util.Optional;

import com.cs.speedtest.entities.MetricGatewayHistory;
import com.cs.speedtest.repository.MetricGatewayHistoryRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Spring persistence service for "MetricGatewayHistory" <br>
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Service
@Transactional
public class MetricGatewayHistoryPersistenceService  {

	@Autowired
	private MetricGatewayHistoryRepository metricGatewayHistoryRepository;


	
	public MetricGatewayHistory findById(String guid) {

		Optional<MetricGatewayHistory> optionalEntity = metricGatewayHistoryRepository.findById(guid);
		if ( optionalEntity.isPresent() ) {
			return optionalEntity.get();
		}
		return null ;

	}

	
	public List<MetricGatewayHistory> findAll() {
		//return mapper.mapEntityToRecord(metricGatewayHistoryRepository.findAll());

		List<MetricGatewayHistory> entities = metricGatewayHistoryRepository.findAll() ;
		List<MetricGatewayHistory> records = new java.util.LinkedList<MetricGatewayHistory>();
		for ( MetricGatewayHistory entity : entities ) {
			records.add( entity ) ;
		}
		return records ;

	}

	
	public long countAll() {
		return metricGatewayHistoryRepository.count();
	}

	
	public MetricGatewayHistory save(MetricGatewayHistory record) {
//		return mapper.map(metricGatewayHistoryRepository.save(mapper.map(record)));
		MetricGatewayHistory saved = metricGatewayHistoryRepository.save( record );
		return saved;

	}

	
	public boolean update(MetricGatewayHistory record) {

		if ( exists(record) ) {
			metricGatewayHistoryRepository.save(record);
			return true;
		}
		return false;
	}

	
	public MetricGatewayHistory create(MetricGatewayHistory record) {
		MetricGatewayHistory saved = metricGatewayHistoryRepository.save( record );
		return saved;

	}

	
	public boolean deleteById(String guid) {
		final Optional<MetricGatewayHistory> optinalEntity = metricGatewayHistoryRepository.findById(guid);
		if( ! optinalEntity.isPresent() ) {
			return false;
		}

		else {
			metricGatewayHistoryRepository.delete(optinalEntity.get());
			return true;
		}
	}

	
	public boolean delete(MetricGatewayHistory record) {
		if(record == null) {
			return false;
		}
		return deleteById( record.getGuid() );

	}

	
	public boolean exists(String guid) {
		return metricGatewayHistoryRepository.findById(guid).isPresent();
	}

	
	public boolean exists(MetricGatewayHistory record) {
		return record == null ? false : metricGatewayHistoryRepository.findById(record.getGuid()).isPresent();
	}

}
