/*
 * Created on 2022-06-09 ( Date ISO 2022-06-09 - Time 21:05:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.service;

import java.util.List;
import java.util.Optional;

import com.cs.speedtest.entities.MetricGatewayConfig;
import com.cs.speedtest.repository.MetricGatewayConfigRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Spring persistence service for "MetricGatewayConfig" <br>
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Service
@Transactional
public class MetricGatewayConfigPersistenceService  {

	@Autowired
	private MetricGatewayConfigRepository metricGatewayConfigRepository;


	public MetricGatewayConfig findById(String guid) {

		Optional<MetricGatewayConfig> optionalEntity = metricGatewayConfigRepository.findById(guid);
		if ( optionalEntity.isPresent() ) {
			return optionalEntity.get();
		}
		return null ;

	}

	
	public List<MetricGatewayConfig> findAll() {
		//return mapper.mapEntityToRecord(metricGatewayConfigRepository.findAll());

		List<MetricGatewayConfig> entities = metricGatewayConfigRepository.findAll() ;
		List<MetricGatewayConfig> records = new java.util.LinkedList<MetricGatewayConfig>();
		for ( MetricGatewayConfig entity : entities ) {
			records.add( entity ) ;
		}
		return records ;

	}

	
	public long countAll() {
		return metricGatewayConfigRepository.count();
	}

	
	public MetricGatewayConfig save(MetricGatewayConfig record) {
//		return mapper.map(metricGatewayConfigRepository.save(mapper.map(record)));
		MetricGatewayConfig saved = metricGatewayConfigRepository.save(record );
		return saved;

	}

	
	public boolean update(MetricGatewayConfig record) {

		if ( exists(record) ) {
			metricGatewayConfigRepository.save(record);
			return true;
		}
		return false;
	}

	
	public MetricGatewayConfig create(MetricGatewayConfig record) {
		MetricGatewayConfig saved = metricGatewayConfigRepository.save( record );
		return saved;

	}

	
	public boolean deleteById(String guid) {
		final Optional<MetricGatewayConfig> optinalEntity = metricGatewayConfigRepository.findById(guid);
		if( ! optinalEntity.isPresent() ) {
			return false;
		}

		else {
			metricGatewayConfigRepository.delete(optinalEntity.get());
			return true;
		}
	}

	
	public boolean delete(MetricGatewayConfig record) {
		if(record == null) {
			return false;
		}
		return deleteById( record.getGuid() );

	}

	
	public boolean exists(String guid) {
		return metricGatewayConfigRepository.findById(guid).isPresent();
	}

	
	public boolean exists(MetricGatewayConfig record) {
		return record == null ? false : metricGatewayConfigRepository.findById(record.getGuid()).isPresent();
	}

}
