/*
 * Created on 2022-06-09 ( Date ISO 2022-06-09 - Time 21:05:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.cs.speedtest.service;

import java.util.List;
import java.util.Optional;

import com.cs.speedtest.entities.SpeedTest;
import com.cs.speedtest.repository.SpeedTestRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Spring persistence service for "SpeedTest" <br>
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Service
@Transactional
public class SpeedTestPersistenceService  {

	@Autowired
	private SpeedTestRepository speedTestRepository;

	
	public SpeedTest findById(String guid) {

		Optional<SpeedTest> optionalEntity = speedTestRepository.findById(guid);
		if ( optionalEntity.isPresent() ) {
			return optionalEntity.get();
		}
		return null ;

	}

	
	public List<SpeedTest> findAll() {
		//return speedTestRepository.findAll());

		List<SpeedTest> entities = speedTestRepository.findAll() ;
		List<SpeedTest> records = new java.util.LinkedList<SpeedTest>();
		for ( SpeedTest entity : entities ) {
			records.add( entity ) ;
		}
		return records ;

	}

	
	public long countAll() {
		return speedTestRepository.count();
	}

	
	public SpeedTest save(SpeedTest record) {
//		return mapper.map(speedTestRepository.save(mapper.map(record)));
		SpeedTest saved = speedTestRepository.save(record );
		return saved;

	}

	
	public boolean update(SpeedTest record) {

		if ( exists(record) ) {
			speedTestRepository.save(record);
			return true;
		}
		return false;
	}

	
	public SpeedTest create(SpeedTest record) {
		SpeedTest saved = speedTestRepository.save(record );
		return saved;

	}

	
	public boolean deleteById(String guid) {
		final Optional<SpeedTest> optinalEntity = speedTestRepository.findById(guid);
		if( ! optinalEntity.isPresent() ) {
			return false;
		}

		else {
			speedTestRepository.delete(optinalEntity.get());
			return true;
		}
	}

	
	public boolean delete(SpeedTest record) {
		if(record == null) {
			return false;
		}
		return deleteById( record.getGuid() );

	}

	
	public boolean exists(String guid) {
		return speedTestRepository.findById(guid).isPresent();
	}

	
	public boolean exists(SpeedTest record) {
		return record == null ? false : speedTestRepository.findById(record.getGuid()).isPresent();
	}

}
