/*
 * Created on 2022-06-09 ( Date ISO 2022-06-09 - Time 11:07:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.persistence.commons;

/**
 * The pattern defined here is used by the Persistence Service Provider <br>
 * to build the service implementation class name <br>
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class PersistenceSpringDataJpaServicePattern {

	public final static String  PATTERN = "%s.impl.springdatajpa.service.%sService" ;
	
}
